# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  About: /about
  Github: https://github.com/nevins-b
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics: "UA-33814773-2"
favicon: /favicon.ico

twitter: http206
